name: reverse_image_search_infrastructure_workflow

on:
  push:
    branches:
    - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'ASSIGNMENT.md'

permissions:
  id-token: write
  contents: read

jobs:
  

  deploy:
    name: Continuous Delivery
    needs: [tf_training_server_image_build, api_server_image_build, terraform_code_validation, terrascan]
    runs-on: ubuntu-latest
    env:
          ARM_TENANT_ID: ${{ secrets.az_tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.az_subscription_id }}
          ARM_CLIENT_ID: ${{ secrets.az_client_id }}
          ARM_CLIENT_SECRET: ${{ secrets.az_client_secret }}
          ARM_ACCESS_KEY: ${{ secrets.az_account_key }}
          TF_VAR_public_key: ${{ secrets.tf_var_public_key }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Run tf-training-server Creation
        run: |
          cd infrastructure/tf-training-server/
          terraform init 
          terraform apply --auto-approve
          terraform destroy --auto-approve

